---
title: "First Knit"
author: "Precious Calderon"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
  word_document:
    toc: yes
    toc_depth: '5'
  pdf_document:
    toc: yes
    toc_depth: '5'
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I went to Eastside High School, but I'm originally from the Philippines. I spent 17 years there and then moved here to the US. I only attended Eastside for one semester and graduated soon after. Between Math and English, I find the former easier than the latter. But among all subjects, I do best in and enjoy Chemistry the most. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I use a MacBook Air that I've recently purchased. Because I've only been using this computer for about 5 months, I'd say my skills would be at a 6 out of 10. I have basic knowledge in terms of using this computer, but I still have a lot to go in using it efficiently. My internet access is fairly ok. Not the fastest, but fast enough to get things done in time.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called by my first name "Precious". Some of my friends call me by my nicknames "Precy" or "PJ", but in the class, my first name would be the most appropriate. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
After college, I'm hoping to become a Clinical Laboratory Scientist or become a researcher. I enjoy studying Biology and Chemistry, and both of these subjects are used in the careers I intend to pursue. Aside from getting a bachelor's degree in Biochemistry, I also want to achieve either a master's degree or a doctorate in the previously mentioned fields.But generally, I aspire to get a stable job in the future to support myself and my family.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
As mentioned earlier, I'm from the Philippines, and I moved here in December of 2019. In the 17 years I've lived there, I visited a lot of places, but I particularly like the beaches we have there. I would love to go back there to visit my family. I would also like to visit other Asian countries like Japan or Korea in the future. I've never been in the military, but if I were drafted, I would join the Navy because I think it would be interesting to live in and operate a submarine.    
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




